## Next Word Prediction Using LSTM
#### Project Overview:

This project aims to develop a deep learning model for predicting the next word in a given sequence of words. The model is built using Long Short-Term Memory (LSTM) networks, which are well-suited for sequence prediction tasks. The project includes the following steps:

1- Data Collection: We use the text of Shakespeare's "Hamlet" as our dataset. This rich, complex text provides a good challenge for our model.

2- Data Preprocessing: The text data is tokenized, converted into sequences, and padded to ensure uniform input lengths. The sequences are then split into training and testing sets.

3- Model Building: An LSTM model is constructed with an embedding layer, two LSTM layers, and a dense output layer with a softmax activation function to predict the probability of the next word.

4- Model Training: The model is trained using the prepared sequences, with early stopping implemented to prevent overfitting. Early stopping monitors the validation loss and stops training when the loss stops improving.

5- Model Evaluation: The model is evaluated using a set of example sentences to test its ability to predict the next word accurately.

6- Deployment: A Streamlit web application is developed to allow users to input a sequence of words and get the predicted next word in real-time.

In [1]:
## Data Collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import  pandas as pd

## load the dataset
data=gutenberg.raw('CrimeAndPunishment.txt')
## save to a file
with open('CrimeAndPunishment.txt','w') as file:
    file.write(data)

[nltk_data] Downloading package gutenberg to
[nltk_data]     /Users/saurav/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.


In [2]:
## Data Preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

##laod the dataset
with open('CrimeAndPunishment.txt','r') as file:
    text=file.read().lower()

## Tokenize the text-creating indexes for words
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
total_words



10167

In [3]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'he': 4,
 'a': 5,
 'â\x80\x9d': 6,
 'of': 7,
 'you': 8,
 'i': 9,
 'in': 10,
 'it': 11,
 'that': 12,
 'was': 13,
 'his': 14,
 'at': 15,
 'her': 16,
 'not': 17,
 'with': 18,
 'but': 19,
 'for': 20,
 'she': 21,
 'him': 22,
 'had': 23,
 'on': 24,
 'is': 25,
 'all': 26,
 'as': 27,
 'have': 28,
 'be': 29,
 'me': 30,
 'what': 31,
 'so': 32,
 'are': 33,
 'my': 34,
 'they': 35,
 'from': 36,
 'raskolnikov': 37,
 'there': 38,
 'were': 39,
 'out': 40,
 'this': 41,
 'up': 42,
 'your': 43,
 'one': 44,
 'them': 45,
 'no': 46,
 'been': 47,
 'would': 48,
 'do': 49,
 'now': 50,
 'by': 51,
 'if': 52,
 'an': 53,
 'am': 54,
 'will': 55,
 'know': 56,
 'about': 57,
 'said': 58,
 'too': 59,
 'could': 60,
 'did': 61,
 'how': 62,
 'man': 63,
 'like': 64,
 'come': 65,
 'only': 66,
 'very': 67,
 'though': 68,
 'then': 69,
 'when': 70,
 'donâ\x80\x99t': 71,
 'or': 72,
 'more': 73,
 'again': 74,
 'into': 75,
 'â\x80\x9ci': 76,
 'some': 77,
 'time': 78,
 'itâ\x80\x99s': 79,
 'we': 80

In [4]:
## create inoput sequences
input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)

        

In [5]:
input_sequences

[[24, 53],
 [24, 53, 3210],
 [24, 53, 3210, 1354],
 [24, 53, 3210, 1354, 429],
 [24, 53, 3210, 1354, 429, 1891],
 [24, 53, 3210, 1354, 429, 1891, 10],
 [24, 53, 3210, 1354, 429, 1891, 10, 6123],
 [24, 53, 3210, 1354, 429, 1891, 10, 6123, 5],
 [24, 53, 3210, 1354, 429, 1891, 10, 6123, 5, 247],
 [24, 53, 3210, 1354, 429, 1891, 10, 6123, 5, 247, 63],
 [24, 53, 3210, 1354, 429, 1891, 10, 6123, 5, 247, 63, 124],
 [24, 53, 3210, 1354, 429, 1891, 10, 6123, 5, 247, 63, 124, 40],
 [24, 53, 3210, 1354, 429, 1891, 10, 6123, 5, 247, 63, 124, 40, 7],
 [1, 1742],
 [1, 1742, 10],
 [1, 1742, 10, 91],
 [1, 1742, 10, 91, 4],
 [1, 1742, 10, 91, 4, 2778],
 [1, 1742, 10, 91, 4, 2778, 10],
 [1, 1742, 10, 91, 4, 2778, 10, 6124],
 [1, 1742, 10, 91, 4, 2778, 10, 6124, 238],
 [1, 1742, 10, 91, 4, 2778, 10, 6124, 238, 2],
 [1, 1742, 10, 91, 4, 2778, 10, 6124, 238, 2, 263],
 [1, 1742, 10, 91, 4, 2778, 10, 6124, 238, 2, 263, 678],
 [1, 1742, 10, 91, 4, 2778, 10, 6124, 238, 2, 263, 678, 27],
 [1, 1742, 10, 91, 4, 2

In [6]:
## Pad Sequences
max_sequence_len=max([len(x) for x in input_sequences])
max_sequence_len

18

In [7]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,   24,   53],
       [   0,    0,    0, ...,   24,   53, 3210],
       [   0,    0,    0, ...,   53, 3210, 1354],
       ...,
       [   0,    0,    0, ...,   19,  208,  414],
       [   0,    0,    0, ...,  208,  414,  534],
       [   0,    0,    0, ...,  414,  534,   25]], dtype=int32)

In [8]:
##create predicitors and label
import tensorflow as tf
x,y=input_sequences[:,:-1],input_sequences[:,-1]

In [9]:
x

array([[   0,    0,    0, ...,    0,    0,   24],
       [   0,    0,    0, ...,    0,   24,   53],
       [   0,    0,    0, ...,   24,   53, 3210],
       ...,
       [   0,    0,    0, ...,  534,   19,  208],
       [   0,    0,    0, ...,   19,  208,  414],
       [   0,    0,    0, ...,  208,  414,  534]], dtype=int32)

In [10]:
y

array([  53, 3210, 1354, ...,  414,  534,   25], dtype=int32)

In [11]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [13]:
# Define early stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

In [14]:
## Train our LSTM RNN

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,GRU

## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.summary()

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
## GRU RNN
## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(GRU(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
## Train the model
history=model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test),verbose=1,callbacks=[early_stopping])


: 

In [16]:
# Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [17]:
input_text="To be or not to be"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:To be or not to be
Next Word PRediction:the


In [18]:
## Save the model
model.save("next_word_lstm.h5")
## Save the tokenizer
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

In [19]:
input_text="  Barn. Last night of all,When yond same"
print(f"Input text:{input_text}")
max_sequence_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_sequence_len)
print(f"Next Word PRediction:{next_word}")

Input text:  Barn. Last night of all,When yond same
Next Word PRediction:lord
